name: Deploy Static Website

on:
  push:
    branches: [main] # Adjust the branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          build_dir: public/ # Specify the directory containing your built website
